[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bascula"
version = "0.0.0"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
include = ["bascula*", "pantalla_reloj*"]
