name: CI (manual)

on:
  workflow_dispatch:

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck python3

      - name: Shellcheck
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(scripts/*.sh overlay/x735/*.sh packaging/postinst)
          ((${#files[@]})) && shellcheck "${files[@]}" || echo "No shell scripts to lint"

      - name: Bash syntax checks
        run: |
          set -euo pipefail
          for f in scripts/install-1-system.sh scripts/smoke.sh overlay/x735/x735-fan.sh overlay/x735/x735-poweroff.sh packaging/postinst; do
            [[ -f "$f" ]] && bash -n "$f"
          done

      - name: config.txt dry-run (idempotence)
        run: |
          set -euo pipefail
          tmp="$(mktemp)"
          cat >"$tmp" <<'CFG'
          dtoverlay=vc4-kms-v3d
          dtparam=audio=on
          CFG
          python3 tools/update-config.py "$tmp"
          a="$(sha256sum "$tmp" | awk '{print $1}')"
          python3 tools/update-config.py "$tmp"
          b="$(sha256sum "$tmp" | awk '{print $1}')"
          if [[ "$a" != "$b" ]]; then
            echo "::error::tools/update-config.py is not idempotent"
            exit 1
          fi

      - name: Optional systemd-analyze
        run: |
          set -euo pipefail
          if command -v systemd-analyze >/dev/null 2>&1; then
            systemd-analyze verify systemd/x735-fan.service systemd/x735-poweroff.service systemd/bascula-app.service || true
          else
            echo "systemd-analyze not available on runner"
          fi
