name: ci-min
on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dirs
        run: mkdir -p /tmp/ci-root /tmp/ci-logs && chmod -R 777 /tmp/ci-root /tmp/ci-logs
      - name: Install shells tooling
        run: sudo apt-get update && sudo apt-get install -y bash coreutils grep sed findutils
      - name: CI install-1
        env:
          BASCULA_CI: "1"
          DESTDIR: "/tmp/ci-root"
        run: bash scripts/install-1-system.sh
      - name: CI install-2
        env:
          BASCULA_CI: "1"
          DESTDIR: "/tmp/ci-root"
        run: bash scripts/install-2-app.sh
      - name: Run minimal tests
        env:
          BASCULA_CI: "1"
          DESTDIR: "/tmp/ci-root"
        run: bash ci/tests/test_min.sh
      - name: Run bascula-app unit guards test
        env:
          BASCULA_CI: "1"
          DESTDIR: "/tmp/ci-root"
        run: bash ci/tests/test_app_unit.sh
      - name: Run UART legacy test
        env:
          BASCULA_CI: "1"
          DESTDIR: "/tmp/ci-root"
        run: bash ci/tests/test_uart.sh
      - name: Run x735 unit test
        env:
          BASCULA_CI: "1"
          DESTDIR: "/tmp/ci-root"
        run: bash ci/tests/test_x735.sh
      - name: Run Python deps test
        env:
          BASCULA_CI: "1"
          DESTDIR: "/tmp/ci-root"
        run: bash ci/tests/test_deps.sh
      - name: Run safe_run recovery tests
        env:
          BASCULA_CI: "1"
          DESTDIR: "/tmp/ci-root"
        run: bash ci/tests/test_safe_run.sh
      - name: Run bascula APP_READY guard test
        env:
          BASCULA_CI: "1"
          DESTDIR: "/tmp/ci-root"
        run: bash ci/tests/test_app_ready.sh
      - name: Run early heartbeat test
        env:
          BASCULA_CI: "1"
          DESTDIR: "/tmp/ci-root"
        run: bash ci/tests/test_early_heartbeat.sh
      - name: Run theme lint
        run: python scripts/lint_theme.py
      - name: Run UI structural probe
        run: |
          sudo apt-get update && sudo apt-get install -y xvfb
          xvfb-run -a python ci/ui_probe.py
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            /tmp/ci-logs
            /tmp/ci-root/etc/systemd/system
            ci-logs/ui_geometry.json
