name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shellcheck scripts
        run: |
          shellcheck scripts/*.sh overlay/x735/*.sh

      - name: Bash syntax validation
        run: |
          bash -n scripts/install-1-system.sh packaging/postinst

      - name: config.txt dry-run
        run: |
          tmp_config="$(mktemp)"
          cat <<'CFG' >"${tmp_config}"
[all]
dtoverlay=vc4-kms-v3d
dtparam=audio=on
CFG
          python3 tools/update-config.py "${tmp_config}"
          first_sum="$(sha256sum "${tmp_config}" | awk '{print $1}')"
          python3 tools/update-config.py "${tmp_config}"
          second_sum="$(sha256sum "${tmp_config}" | awk '{print $1}')"
          if [ "${first_sum}" != "${second_sum}" ]; then
            echo "Config update is not idempotent" >&2
            diff -u <(echo "${first_sum}") <(echo "${second_sum}") || true
            exit 1
          fi
          echo "Final config:" >&2
          cat "${tmp_config}" >&2

      - name: Optional systemd-analyze verify
        run: |
          if command -v systemd-analyze >/dev/null 2>&1; then
            systemd-analyze verify systemd/x735-fan.service systemd/x735-poweroff.service systemd/bascula-app.service || true
          else
            echo "systemd-analyze no disponible en runner" >&2
          fi
